import type { Metadata } from "next";
import "../../globals.css";
import Link from "next/link";
import Image from "next/image";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardFooter } from "@/components/ui/card";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const SignInButton: React.FC = () => {
  return (
    <Button type="submit" size="lg" className="w-full">
      {"Sign In"}
    </Button>
  );
};

const SignUpButton: React.FC = () => {
  return (
    <Button type="submit" size="lg" className="w-full">
      {"Sign Up"}
    </Button>
  );
};

export default function RootLayout({}: // children,
Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <section
      id="Signup"
      className="bg-[url('/assets/images/background/airplane.png')] bg-no-repeat bg-cover bg-left-top -z-10 min-h-screen"
    >
      <div className="Header-content bg-gradient-to-r from-[#080318] to-[rgba(8,3,24,0)] z=0 min-h-screen">
        <nav
          id="Navbar"
          className="container max-w-[1130px] mx-auto flex justify-between items-center pt-[30px]"
        >
          <Link href="index.html" className="flex items-center shrink-0">
            <Image
              width={120}
              height={60}
              src="/assets/images/logos/logo.svg"
              alt="logo"
            />
          </Link>
          <ul className="nav-menus flex gap-[30px] items-center w-fit">
            <li>
              <Link href="" className="font-medium">
                Flash Sale
              </Link>
            </li>
            <li>
              <Link href="" className="font-medium">
                Discover
              </Link>
            </li>
            <li>
              <Link href="" className="font-medium">
                Packages
              </Link>
            </li>
            <li>
              <Link href="" className="font-medium">
                Stories
              </Link>
            </li>
            <li>
              <Link href="" className="font-medium">
                About
              </Link>
            </li>
            <Link
              href="signin.html"
              className="font-bold text-flysha-black bg-flysha-light-purple rounded-full p-[12px_30px] transition-all duration-300 hover:shadow-[0_10px_20px_0_#B88DFF]"
            >
              Sign In
            </Link>
          </ul>
        </nav>
        <div className="flex flex-col justify-between min-h-[calc(100vh-78px)]">
          <div className="form-section container max-w-[1130px] w-full mx-auto flex flex-col gap-[30px] mt-[53px]">
            <div className="title flex flex-col gap-1">
              <h1 className="font-bold text-[32px] leading-[48px]">Sign In</h1>
              <p className="font-medium text-lg leading-[27px]">
                Enjoy new experience of flight
              </p>
            </div>
            <div className="flex min-h-full flex-1 flex-col justify-center">
              <Tabs defaultValue="signin" className="w-[480px]">
                <TabsList className="grid w-full grid-cols-2">
                  <TabsTrigger value="signin">Sign In</TabsTrigger>
                  <TabsTrigger value="signup">Sign Up</TabsTrigger>
                </TabsList>
                <TabsContent value="signin">
                  <Card>
                    <form>
                      <CardContent className="space-y-2 w-full p-6">
                        <div className="space-y-1">
                          <Label htmlFor="email">Email</Label>
                          <Input
                            type="email"
                            id="email"
                            name="email"
                            placeholder="Enter Email"
                          />
                        </div>
                        <div className="space-y-1">
                          <Label htmlFor="password">Password</Label>
                          <Input
                            type="password"
                            id="password"
                            name="password"
                            placeholder="Enter Password"
                          />
                        </div>
                      </CardContent>
                      <CardFooter>
                        <SignInButton />
                      </CardFooter>
                    </form>
                  </Card>
                </TabsContent>
                <TabsContent value="signup">
                  <Card>
                    <form>
                      <CardContent className="space-y-2 w-full p-6">
                        <div className="flex gap-3 items-center w-full">
                          <div className="space-y-1 w-full">
                            <Label htmlFor="name">Full Name</Label>
                            <Input
                              type="text"
                              required
                              id="name"
                              name="name"
                              placeholder="Enter Full Name"
                            />
                          </div>
                          <div className="space-y-1 w-full">
                            <Label htmlFor="passport">Passport</Label>
                            <Input
                              type="passport"
                              required
                              id="passport"
                              name="passport"
                              placeholder="Enter Passport"
                            />
                          </div>
                        </div>
                        <div className="flex gap-3 items-center w-full">
                          <div className="space-y-1 w-full">
                            <Label htmlFor="email">Email</Label>
                            <Input
                              type="email"
                              required
                              id="email"
                              name="email"
                              placeholder="Enter Email"
                            />
                          </div>
                          <div className="space-y-1 w-full">
                            <Label htmlFor="password">Password</Label>
                            <Input
                              type="password"
                              required
                              id="password"
                              name="password"
                              placeholder="Enter Password"
                            />
                          </div>
                        </div>
                      </CardContent>
                      <CardFooter>
                        <SignUpButton />
                      </CardFooter>
                    </form>
                  </Card>
                </TabsContent>
              </Tabs>
            </div>
          </div>
          <div className="company-logos w-full flex items-center py-[50px] bottom-0 overflow-hidden">
            <div className="slider flex shrink-0 w-max">
              <div className="animate-[slide_10s_linear_infinite] flex gap-[50px] pl-[50px] items-center">
                <div className="flex w-fit h-[30px] shrink-0">
                  <Image
                    width={120}
                    height={60}
                    src="/assets/images/logos/logoipsum1.png"
                    className="w-full h-full object-contain"
                    alt="logo"
                  />
                </div>
                <div className="flex w-fit h-[30px] shrink-0">
                  <Image
                    width={120}
                    height={60}
                    src="/assets/images/logos/logoipsum2.png"
                    className="w-full h-full object-contain"
                    alt="logo"
                  />
                </div>
                <div className="flex w-fit h-[30px] shrink-0">
                  <Image
                    width={120}
                    height={60}
                    src="/assets/images/logos/logoipsum3.png"
                    className="w-full h-full object-contain"
                    alt="logo"
                  />
                </div>
                <div className="flex w-fit h-[30px] shrink-0">
                  <Image
                    width={120}
                    height={60}
                    src="/assets/images/logos/logoipsum4.png"
                    className="w-full h-full object-contain"
                    alt="logo"
                  />
                </div>
                <div className="flex w-fit h-[30px] shrink-0">
                  <Image
                    width={120}
                    height={60}
                    src="/assets/images/logos/logoipsum1.png"
                    className="w-full h-full object-contain"
                    alt="logo"
                  />
                </div>
                <div className="flex w-fit h-[30px] shrink-0">
                  <Image
                    width={120}
                    height={60}
                    src="/assets/images/logos/logoipsum2.png"
                    className="w-full h-full object-contain"
                    alt="logo"
                  />
                </div>
                <div className="flex w-fit h-[30px] shrink-0">
                  <Image
                    width={120}
                    height={60}
                    src="/assets/images/logos/logoipsum3.png"
                    className="w-full h-full object-contain"
                    alt="logo"
                  />
                </div>
                <div className="flex w-fit h-[30px] shrink-0">
                  <Image
                    width={120}
                    height={60}
                    src="/assets/images/logos/logoipsum4.png"
                    className="w-full h-full object-contain"
                    alt="logo"
                  />
                </div>
              </div>
              <div className="animate-[slide_10s_linear_infinite] flex gap-[50px] pl-[50px] items-center">
                <div className="flex w-fit h-[30px] shrink-0">
                  <Image
                    width={120}
                    height={60}
                    src="/assets/images/logos/logoipsum1.png"
                    className="w-full h-full object-contain"
                    alt="logo"
                  />
                </div>
                <div className="flex w-fit h-[30px] shrink-0">
                  <Image
                    width={120}
                    height={60}
                    src="/assets/images/logos/logoipsum2.png"
                    className="w-full h-full object-contain"
                    alt="logo"
                  />
                </div>
                <div className="flex w-fit h-[30px] shrink-0">
                  <Image
                    width={120}
                    height={60}
                    src="/assets/images/logos/logoipsum3.png"
                    className="w-full h-full object-contain"
                    alt="logo"
                  />
                </div>
                <div className="flex w-fit h-[30px] shrink-0">
                  <Image
                    width={120}
                    height={60}
                    src="/assets/images/logos/logoipsum4.png"
                    className="w-full h-full object-contain"
                    alt="logo"
                  />
                </div>
                <div className="flex w-fit h-[30px] shrink-0">
                  <Image
                    width={120}
                    height={60}
                    src="/assets/images/logos/logoipsum1.png"
                    className="w-full h-full object-contain"
                    alt="logo"
                  />
                </div>
                <div className="flex w-fit h-[30px] shrink-0">
                  <Image
                    width={120}
                    height={60}
                    src="/assets/images/logos/logoipsum2.png"
                    className="w-full h-full object-contain"
                    alt="logo"
                  />
                </div>
                <div className="flex w-fit h-[30px] shrink-0">
                  <Image
                    width={120}
                    height={60}
                    src="/assets/images/logos/logoipsum3.png"
                    className="w-full h-full object-contain"
                    alt="logo"
                  />
                </div>
                <div className="flex w-fit h-[30px] shrink-0">
                  <Image
                    width={120}
                    height={60}
                    src="/assets/images/logos/logoipsum4.png"
                    className="w-full h-full object-contain"
                    alt="logo"
                  />
                </div>
              </div>
              <div className="animate-[slide_10s_linear_infinite] flex gap-[50px] pl-[50px] items-center">
                <div className="flex w-fit h-[30px] shrink-0">
                  <Image
                    width={120}
                    height={60}
                    src="/assets/images/logos/logoipsum1.png"
                    className="w-full h-full object-contain"
                    alt="logo"
                  />
                </div>
                <div className="flex w-fit h-[30px] shrink-0">
                  <Image
                    width={120}
                    height={60}
                    src="/assets/images/logos/logoipsum2.png"
                    className="w-full h-full object-contain"
                    alt="logo"
                  />
                </div>
                <div className="flex w-fit h-[30px] shrink-0">
                  <Image
                    width={120}
                    height={60}
                    src="/assets/images/logos/logoipsum3.png"
                    className="w-full h-full object-contain"
                    alt="logo"
                  />
                </div>
                <div className="flex w-fit h-[30px] shrink-0">
                  <Image
                    width={120}
                    height={60}
                    src="/assets/images/logos/logoipsum4.png"
                    className="w-full h-full object-contain"
                    alt="logo"
                  />
                </div>
                <div className="flex w-fit h-[30px] shrink-0">
                  <Image
                    width={120}
                    height={60}
                    src="/assets/images/logos/logoipsum1.png"
                    className="w-full h-full object-contain"
                    alt="logo"
                  />
                </div>
                <div className="flex w-fit h-[30px] shrink-0">
                  <Image
                    width={120}
                    height={60}
                    src="/assets/images/logos/logoipsum2.png"
                    className="w-full h-full object-contain"
                    alt="logo"
                  />
                </div>
                <div className="flex w-fit h-[30px] shrink-0">
                  <Image
                    width={120}
                    height={60}
                    src="/assets/images/logos/logoipsum3.png"
                    className="w-full h-full object-contain"
                    alt="logo"
                  />
                </div>
                <div className="flex w-fit h-[30px] shrink-0">
                  <Image
                    width={120}
                    height={60}
                    src="/assets/images/logos/logoipsum4.png"
                    className="w-full h-full object-contain"
                    alt="logo"
                  />
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}
