import type { Metadata } from "next";
// import { Toaster } from "@/components/ui/toaster";
import "../../globals.css";
// import { ThemeProvider } from "@/components/themeProvider";
import Navbar from "./components/navbar";
import RunningCompany from "./components/runningCompany";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: // children,
Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      {/* <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
        <Toaster />
      </body> */}
      <body className={`text-white font-poppins bg-flysha-black`}>
        <section
          id="Signup"
          className="bg-[url('/assets/images/background/airplane.png')] bg-no-repeat bg-cover bg-left-top -z-10 min-h-screen"
        >
          <div className="Header-content bg-gradient-to-r from-[#080318] to-[rgba(8,3,24,0)] z=0 min-h-screen">
            <Navbar />
            <div className="flex flex-col justify-between min-h-[calc(100vh-78px)]">
              {children}
              <RunningCompany />
            </div>
          </div>
        </section>
      </body>
    </html>
  );
}
